server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://db.youngcloud.top:3306/framework_net
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl