server:
  port: 8081
swagger:
  enable: true
spring:
  datasource:
    url: jdbc:mysql://db.youngcloud.top:3306/framework_net
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  spring:
    servlet:
      multipart:
        enabled: true
        max-file-size: 20MB
        max-request-size: 20MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl